@startuml
'https://plantuml.com/class-diagram

interface Builder {
    + buildPartA()
    + buildPartB()
    + buildPartC()
    + getResult()
}

class ConcreteBuilder {
    + buildPartA()
    + buildPartB()
    + buildPartC()
    + getResult()
}

class Director {
    - create.builder: Builder
    + construct()
}

Director o--> Builder


class Product

Builder <|-- ConcreteBuilder
Product <.. ConcreteBuilder

note left of Director::construct
    create.builder.buildPartA();
    create.builder.buildPartB();
    create.builder.buildPartC();
    return create.builder.getResult();
end note

@enduml