@startuml
'https://plantuml.com/class-diagram

class EmailSender {
    +send(Customer): void
}

abstract class Customer {
    -name: String
    -email: String
    +getName(): String
    +setName(): void
    +getEmail(): String
    +setEmail(): void
}

class CommonCustomer
class VIPCustomer

Customer <|-- CommonCustomer
Customer <|-- VIPCustomer

Customer <.. EmailSender

@enduml