@startuml
'https://plantuml.com/class-diagram

class DBUtil {
    +getConnection(): Connection
}

class OracleDBUtil
class MysqlDBUtil
DBUtil <|-- OracleDBUtil
DBUtil <|-- MysqlDBUtil

class CustomerDAO {
    -util: DBUtil
    +addCustomer(): void
}

DBUtil <-- CustomerDAO

@enduml