@startuml
'https://plantuml.com/class-diagram

class CustomerDataChart {
    -dao: CustomerDAO
    +createChart(): void
    +displayChart(): void
}

class CustomerDAO {
    -util: DBUtil
    +findCustomer(): List
}

class DBUtil {
    +getConnection(): Connection
}

CustomerDAO <-- CustomerDataChart
DBUtil <-- CustomerDAO

@enduml