@startuml
'https://plantuml.com/class-diagram

class Button

class List
class Label

class ComboBox
class TextBox

class Mediator

List <-- Mediator
Label <-- Mediator
ComboBox <-- Mediator
TextBox <-- Mediator

Button <-- Mediator

@enduml