@startuml
'https://plantuml.com/class-diagram

interface Logger {
    +writeLogger(): void
}

class FileLogger {
    +writeLogger(): void
}

class DatabaseLogger {
    +writeLogger(): void
}

Logger <|-- FileLogger
Logger <|-- DatabaseLogger

interface LoggerFactory {
    +createLogger(): Logger
}

class FileLoggerFactory {
    +createLogger(): Logger
}

class DatabaseLoggerFactory {
    +createLogger(): Logger
}

LoggerFactory <|-- FileLoggerFactory
LoggerFactory <|-- DatabaseLoggerFactory

FileLogger <.. FileLoggerFactory
DatabaseLogger <.. DatabaseLoggerFactory

@enduml